sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
env:
  - LUAJIT=OFF
  - LUAJIT=ON
cache: apt
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-iostreams-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libmysqlclient-dev
      - libpugixml-dev
      - clang-format-3.9
before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
  - make clangformat && source ../verify-format.sh
script: make -j2
