sudo: required
dist: trusty
language: cpp
compiler: gcc
cache: apt
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - liblua5.2-dev
      - libmysqlclient-dev
before_script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
script: make -j2
