language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install libboost-system-dev liblua5.2-dev libgmp3-dev libmysqlclient-dev
script: |
  mkdir build && cd build
  cmake -DCMAKE_BUILD_TYPE=Release ..
  make -j `grep processor /proc/cpuinfo | wc -l`
