image: Visual Studio 2017

shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
		- appveyor.yml

environment:
  BOOST_ROOT: C:\Libraries\boost_1_65_1

install:
  - ps: if (-not (Test-Path tfs-sdk-3.2)) { Start-FileDownload https://static.otland.net/dl/tfs-sdk-3.2.zip; 7z x tfs-sdk-3.2.zip }
  - set TFSSDKDir=%CD%\tfs-sdk-3.2

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - tfs-sdk-3.2 -> appveyor.yml

artifacts:
  - path: vc14\**\theforgottenserver.exe
