name: Lua syntax check

on:
  pull_request:
    paths:
      - data/**.lua
  push:
    branches:
      - master
    paths:
      - data/**.lua

jobs:
  luac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v9
        with:
           luaVersion: "5.3.5"

      - name: Test Lua syntax
        run: find data/ -name '*.lua' -print0 | xargs -0 -n1 luac -p
