name: Release builds with vcpkg

on:
  push:
    tags:
      - v*

jobs:
  unix:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    env:
      VCPKG_FEATURE_FLAGS: luajit

    steps:
      - uses: actions/checkout@v3

      - name: Get latest CMake
        # Using 'latest' branch, the latest CMake is installed.
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        with:
          buildPreset: vcpkg
          buildPresetAdditionalArgs: "['--config Release', '--clean-first']"
          configurePreset: vcpkg
          configurePresetAdditionalArgs: "['-G Ninja']"

      - name: Prepare datapack contents
        run: |
          pwd
          ls -al
          find . -maxdepth 1 ! -name data ! -name config.lua.dist ! -name key.pem ! -name LICENSE ! -name README.md ! -name schema.sql -exec rm -r {} \;
          mv ../build/tfs ../build/tfs.exe* ../build/*.dll .
        shell: bash

      - name: Zip the release files
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          filename: tfs-${{ github.ref_name }}-${{ matrix.os }}.zip
          path: forgottenserver
          directory: ../

      - name: Upload release artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: ../tfs-${{ github.ref_name }}-${{ matrix.os }}.zip
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
