name: XML syntax check

permissions:
  contents: read

on:
  pull_request:
    paths:
      - data/**.xml
  push:
    branches:
      - dev
    paths:
      - data/**.xml

jobs:
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt update -q && sudo apt install -yq libxml2-utils

      - name: Test XML syntax
        run: find data/ -name '*.xml' -print0 | xargs -0 -n1 xmllint --noout
