name: XML syntax check

on:
  pull_request:
    paths:
      - data/**.xml
  push:
    paths:
      - data/**.xml

jobs:
  xmllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt update && sudo apt install -y libxml2-utils

      - name: Test XML syntax
        run: find data/ -name '*.xml' -print0 | xargs -0 -n1 xmllint --noout
